options:
    hostname:
        description: The hostname the service will be presented on
        type: string
    config:
        description: The configuration of the asgen (releases, etc - see config.json)
        type: string
    mirror:
        default: http://archive.ubuntu.com/ubuntu/
    default_snap_channel:
        description: When installing snaps, default to this channel
        type: string
        default: stable
    http_proxy:
    https_proxy:
    no_proxy:
