options:
    rsync-host:
        default: appstream.internal
        description: The hostname or IP to rsync from
        type: string
    external-hostname:
        description: The hostname the service will be presented on
        default: appstream.ubuntu.com
        type: string
