#!/bin/sh

EXTERNAL_HOSTNAME=$(config-get external-hostname)

juju relation-set domain=${EXTERNAL_HOSTNAME}
juju relation-set site_config=$(sed -e "s/@EXTERNAL_HOSTNAME@/${EXTERNAL_HOSTNAME}/" ${CHARM_DIR}/appstream.conf.in)
juju relation-set site_modules="autoindex"
juju relation-set ports=80
juju relation-set enabled=true
