#!/bin/sh

EXTERNAL_HOSTNAME=$(config-get external-hostname)
juju-log "External host is '${EXTERNAL_HOSTNAME}'"

apt-get -y install rsync

mkdir -p /srv/appstream /srv/appstream-new

chown ubuntu:ubuntu /srv/appstream /srv/appstream-new

sed -e "s/@EXTERNAL_HOSTNAME@/${EXTERNAL_HOSTNAME}/" ${CHARM_DIR}/appstream.conf.in > /etc/apache2/sites-available/appstream.conf

a2ensite appstream

/etc/init.d/apache2 reload
