#!/bin/sh

EXTERNAL_HOSTNAME=$(config-get external-hostname)
juju-log "External host is '${EXTERNAL_HOSTNAME}'"

apt-get -y install rsync

mkdir -p /srv/appstream /srv/logs

chown ubuntu:ubuntu /srv/appstream /srv/logs
