#!/bin/sh

BASE_DIR=/srv/data/appstream
FORGET_FILE=${BASE_DIR}/forget

. ${FORGET_FILE}

TAG_TO_FORGET=$(action-get tag)

juju-log "Forgetting all packages with ${TAG_TO_FORGET}"

PKGS=$(${CHARM_DIR}/forget ${TAG_TO_FORGET})

juju-log "Forgetting ${PKGS}"

echo "CLEAN_PKGS=\"${CLEAN_PKGS:+${CLEAN_PKGS} }${PKGS}\"" >> ${FORGET_FILE}
chown ubuntu:ubuntu ${FORGET_FILE}
