#!/bin/bash

set -e

device=$(action-get device)

if [ -z "${device}" ]; then
    juju-log "Device must not be empty"
    exit 1
fi

juju-log "Running mirror-mounted (device is ${device})"

mkdir -p /srv/data
chown ubuntu:ubuntu /srv/data

if ! mount -t ext4 ${device} /srv/data; then
    juju-log 'No filesystem - creating...'
    mkfs.ext4 /dev/vdc
    mount -t ext4 ${device} /srv/data
else
    juju-log 'mounted'
fi

juju-log 'Cloning repository'

cat <<EOF | su - appstream
set -e

cd /srv/data/appstream

if [ ! -d "appstream-dep11" ]; then
    git clone https://github.com/ximion/appstream-dep11.git
fi

if [ ! -d "appstream" ]; then
    virtualenv --system-site-packages -p /usr/bin/python3 appstream
fi

. ${CHARM_DIR}/actions/update
EOF

cat <<EOF | su - ubuntu
mkdir -p appstream-public appstream-workdir/export logs
if [ ! -e appstream-workdir/export/logs ]; then
    ln -sf ../logs appstream-workdir/export/logs
fi

if [ ! -e appstream-public/logs ]; then
    ln -sf ../logs appstream-public/logs
fi
EOF

. ${CHARM_DIR}/hooks/config-changed
