#!/bin/bash

set -e

device=$(action-get device)

if [ -z "${device}" ]; then
    juju-log "Device must not be empty"
    exit 1
fi

juju-log "Running mirror-mounted (device is ${device})"

mkdir -p /srv/data
chown ubuntu:ubuntu /srv/data

UUID=$(blkid -s UUID -o value ${device})
if [ -n "${UUID}" ]; then
       juju-log "Volume is ${UUID}"
       echo "UUID=${UUID} /srv/data ext4 defaults 0 0" >> /etc/fstab
fi

if ! mount /srv/data; then
    juju-log 'No filesystem - creating...'
    mkfs.ext4 ${device}
    UUID=$(blkid -s UUID -o value ${device})
    echo "UUID=${UUID} /srv/data ext4 defaults 0 0" >> /etc/fstab
    mount /srv/data
else
    juju-log 'mounted'
fi

mkdir -p /srv/data/appstream
chown appstream:appstream /srv/data/appstream

mkdir -p /srv/data/mirror
chown ubuntu:ubuntu /srv/data/mirror

juju-log 'Cloning repository'

giturl=$(config-get git-host)

cat <<EOF | su - appstream
set -e

cd /srv/data/appstream

if [ ! -d "appstream-dep11" ]; then
    git clone ${giturl}
fi

if [ ! -d "appstream" ]; then
    virtualenv --system-site-packages -p /usr/bin/python3 appstream
fi
EOF

chown ubuntu:ubuntu /srv/data/appstream

juju-log 'Updating'
. ${CHARM_DIR}/actions/update

cat <<EOF | su - ubuntu

cd /srv/data/appstream

mkdir -p appstream-public appstream-workdir/export logs
if [ ! -e appstream-workdir/export/logs ]; then
    ln -sf ../logs appstream-workdir/export/logs
fi

if [ ! -e appstream-public/logs ]; then
    ln -sf ../logs appstream-public/logs
fi
EOF

. ${CHARM_DIR}/hooks/config-changed
