#!/bin/sh

set -e

BASE_DIR=/srv/data/appstream

BUILD_DIR=${BASE_DIR}/appstream-dep11
VIRTUALENV_DIR=${BASE_DIR}/appstream

juju-log 'Upgrading charm'

if [ -d "${BUILD_DIR}" ]; then
    cat <<EOF | su - appstream
cd ${BUILD_DIR}
git pull
. ${VIRTUALENV_DIR}/bin/activate
python3 setup.py build
python3 setup.py install
EOF

    cd ${BUILD_DIR}
    juju-log 'Now at revision $(git rev-parse HEAD)'
fi
