#!/usr/bin/python3

import gzip
import yaml
import os
import sys

p = set()

for (dirpath, dirnames, filenames) in os.walk('/srv/data/appstream/appstream-public/hints/'):
  for filename in filenames:
    fn = os.path.join (dirpath, filename)
    with gzip.open(fn, 'rb') as f:
      for doc in yaml.load_all (f):
        for hint in doc['Hints']:
          if hint['tag'] == sys.argv[1]:
              p.add(doc['Package'])

for pkg in sorted(p):
    print(pkg)
