#!/bin/sh

set -e

BASE_DIR=/srv/appstream
BUILD_DIR=${BASE_DIR}/appstream-generator

juju-log 'Upgrading charm'

giturl=$(config-get git-host)
branch=$(config-get git-branch)

if [ -d "${BUILD_DIR}" ]; then
    cat <<EOF | su - appstream
cd ${BUILD_DIR}
git remote set-url origin ${giturl}
git fetch origin
git checkout ${branch}
git reset --hard origin/${branch}
git clean -fdx
git submodule update --init
mkdir /tmp/dub-repo
mkdir /tmp/fakehome
cp -dr /usr/include/d/mustache-d /tmp/dub-repo
HOME=/tmp/fakehome dub add-local /tmp/dub-repo/mustache-d 0.1.1
HOME=/tmp/fakehome dub -v --skip-registry=standard build --parallel --compiler=ldc2
EOF

    cd ${BUILD_DIR}
    juju-log "Now at revision $(git rev-parse HEAD)"
fi
