#!/bin/sh

set -e

BASE_DIR=/srv/appstream
BUILD_DIR=${BASE_DIR}/appstream-generator

juju-log 'Upgrading charm'

giturl=$(config-get git-host)
branch=$(config-get git-branch)

if [ ! -d /srv/appstream/as-installed ]; then
    mkdir /srv/appstream/as-installed/
    chown appstream:appstream /srv/appstream/as-installed/
fi
if [ -d "${BUILD_DIR}" ]; then
    cat <<EOF | su - appstream
cd ${BUILD_DIR}
git remote set-url origin ${giturl}
git fetch origin
git checkout ${branch}
git reset --hard origin/${branch}
git clean -fdx
git submodule update --init
if [ ! -d build ]; then
    mkdir build
fi
cd build
meson -Ddownload-js=false --prefix=/srv/appstream/as-installed/
ninja && ninja install
if [ ! -d "/srv/appstream/as-installed/share/appstream/templates/default/static/js" ]; then
    mkdir "/srv/appstream/as-installed/share/appstream/templates/default/static/js"
fi
EOF

    cd ${BUILD_DIR}
    juju-log "Now at revision $(git rev-parse HEAD)"
fi
