#!/bin/sh

set -e

BASE_DIR=/srv/appstream
BUILD_DIR=${BASE_DIR}/appstream-generator

juju-log 'Upgrading charm'

giturl=$(config-get git-host)
branch=$(config-get git-branch)

if [ -d "${BUILD_DIR}" ]; then
    cat <<EOF | su - appstream
cd ${BUILD_DIR}
git remote set-url origin ${giturl}
git fetch origin
git checkout ${branch}
git reset --hard origin/${branch}
git clean -fdx
git submodule update --init
if [ ! -d build ]; then
    mkdir build
fi
cd build
if [ ! -d /srv/appstream/as-installed ]; then
    mkdir /srv/appstream/as-installed/
fi
meson -Ddownload_js=false --prefix=/srv/appstream/as-installed/
ninja && ninja install
EOF

    cd ${BUILD_DIR}
    juju-log "Now at revision $(git rev-parse HEAD)"
fi
