options:
    ip:
        default: 127.0.0.1
        description: The public external IP of the appstream service
        type: string
    hostname:
        description: The hostname the service will be presented on
        type: string
    config:
        description: The configuration of the asgen (releases, etc - see config.json)
        type: string
    mirror:
        default: archive.ubuntu.com
    git-host:
        default: https://github.com/ximion/appstream-generator.git
    git-branch:
        default: master
    http_proxy:
    https_proxy:
    no_proxy:
