#!/usr/bin/python3

import glob
import json
import lzma
import sys

tag = sys.argv[1]

p = set()

for filename in glob.glob('/srv/appstream/appstream-public/hints/*/*/Hints-*.xz'):
    f = lzma.open(filename, 'rt', encoding='utf-8')
    j = json.load(f)
    for (k, (v, pkg)) in {k: (v, pkg) for (d, pkg) in [(f['hints'], f['package']) for f in j] for k, v in d.items()}.items():
        for i in v:
            if i['tag'] == tag:
                    p.add(pkg)

print (' '.join(sorted(p)))
