#!/usr/bin/python3

import glob
import json
import lzma
import sys

tag = sys.argv[1]

p = set()

for filename in glob.glob('/srv/appstream/appstream-public/hints/*/*/Hints-*.xz'):
    f = lzma.open(filename, 'rt', encoding='utf-8')
    j = json.load(f)
    for (k, v) in {k: v for d in [f['hints'] for f in j] for k, v in d.items()}.items():
        for i in v:
            if i['tag'] == tag:
                    p.add(k)

print (' '.join(sorted(p)))
