#!/bin/bash

set -e

if ! grep -qs /home/ubuntu/appstream /proc/mounts; then
        juju-log "/home/ubuntu/appstream is not mounted; skipping initial setup"
        exit 0
fi

juju-log 'Installing config files'

mkdir -p /etc/rsync-juju.d/
cat <<EOF > /etc/rsync-juju.d/appstream.conf
[appstream]
    path = /home/ubuntu/appstream/appstream-public/data
    read only = yes
    list = yes
    uid = appstream
    gid = appstream
EOF

cat <<EOF > /etc/rsync-juju.d/www.conf
[www]
    path = /home/ubuntu/appstream/appstream-public
    read only = yes
    list = yes
    uid = ubuntu
    gid = ubuntu
EOF

cat <<EOF > /etc/rsync-juju.d/logs.conf
[logs]
    path = /home/ubuntu/appstream/logs
    read only = yes
    list = yes
    uid = ubuntu
    gid = ubuntu
EOF

service rsync restart
open-port 873

chown ubuntu:ubuntu /home/ubuntu/appstream

cat <<EOF | su - ubuntu
cd /home/ubuntu/appstream

mkdir -p appstream-public appstream-workdir/export logs
if [ ! -e appstream-workdir/export/logs ]; then
    ln -sf ../logs appstream-workdir/export/logs
fi

if [ ! -e appstream-public/logs ]; then
    ln -sf ../logs appstream-public/logs
fi
EOF
