#!/bin/bash

set -e

INPUT_FILENAME=${CHARM_DIR}/asgen-config.json.in
OUTPUT_FILENAME=/srv/appstream/appstream-workdir/asgen-config.json

if ! grep -qs /srv/appstream /proc/mounts; then
        juju-log 'Deferring config-changed; /srv/appstream is not mounted'
        exit 0
fi

juju-log 'Running config-changed hook'

HOSTNAME=$(config-get hostname)

if [ -n "${HOSTNAME}" ]; then
    juju-log "Got hostname ${HOSTNAME}"
fi

MIRROR=$(config-get mirror)
CONFIG=$(config-get config)
echo "${CONFIG}" | ./generate-config "${MIRROR}" "${HOSTNAME}" > "${OUTPUT_FILENAME}"

juju-log 'Adding proxy settings'

for var in http_proxy https_proxy no_proxy; do
    sed -i "/^${var}/d" /etc/environment
    v=$(config-get ${var})
    if [ -n "${v}" ]; then
        juju-log "Setting ${var}=${v}"
        echo "${var}=${v}" >> /etc/environment
    fi
done


cat <<EOF | su - ubuntu
set -e

sed -e 's/#RELEASES#/${RELEASES}/; s/#PARTIALRELEASES#/${PARTIALRELEASES}/; s/#ARCHES#/${ARCHES}/' ${CHARM_DIR}/update-appstream.sh.in > ~/update-appstream.sh
sed -e 's/#PARTIALRELEASES#/${PARTIALRELEASES}/' ${CHARM_DIR}/check-public-mtimes.in > /srv/appstream/check-public-mtimes
chmod +x /srv/appstream/check-public-mtimes

chmod a+x ~/update-appstream.sh

if ! crontab -l | grep -qs update-appstream; then
    echo "0 * * * * flock -xn ~/lock ~/update-appstream.sh" | crontab -
fi
EOF

