#!/bin/bash

set -e

mount=$(relation-get mountpoint)

if [ -z "$mount" ] ; then
        juju-log "wait for related service to start"
        exit 0
fi

if [ ! -d "${mount}" ]; then
        mkdir -p "${mount}"
fi

${CHARM_DIR}/initial-setup
${CHARM_DIR}/hooks/config-changed
