#!/bin/bash

set -ex

juju-log 'Invoking charm-pre-install hooks'
[ -d exec.d ] && ( for f in exec.d/*/charm-pre-install; do [ -x $f ] && /bin/sh -c "$f"; done )

juju-log 'Installing appstream-generator dependencies'

add-apt-repository -y ppa:laney/appstream

apt update

apt-get -y install libcairo2-dev \
                   libcurl4-gnutls-dev \
                   libgdk-pixbuf2.0-dev \
                   libgirepository1.0-dev \
                   libglib2.0-dev \
                   libpango1.0-dev \
                   librsvg2-dev

apt-get -y install libjs-highlight.js \
                   libjs-jquery \
                   libjs-jquery-flot

apt-get -t xenial-backports -y install gir-to-d \
                                       libarchive-dev \
                                       libappstream-dev \
                                       liblmdb-dev \
                                       libmustache-d-dev \
                                       meson

juju-log 'Installing utilities'

apt-get -y install git dub xz-utils ldc

juju-log 'Installing rsyncd'

apt-get -y install rsync

juju-log 'Installing jq (for forget action)'

apt-get -y install jq

# for storage and ksplice (py2)
apt-get -y install python-yaml python-six

${CHARM_DIR}/initial-setup
