#!/bin/bash

set -ex

juju-log 'Invoking charm-pre-install hooks'
[ -d exec.d ] && ( for f in exec.d/*/charm-pre-install; do [ -x $f ] && /bin/sh -c "$f"; done )

juju-log 'Installing appstream-generator dependencies'

add-apt-repository -y ppa:ubuntu-desktop/appstream-generator

apt update

apt-get -y install libjs-highlight.js \
                   libjs-jquery \
                   libjs-jquery-flot

juju-log 'Installing utilities'

apt-get -y install git dub optipng xz-utils

juju-log 'Installing rsyncd'

apt-get -y install rsync

juju-log 'Installing jq (for forget action)'

apt-get -y install jq

# for storage and ksplice (py2)
apt-get -y install python-yaml python-six

snap install --candidate appstream-generator

${CHARM_DIR}/initial-setup
