#!/bin/sh

set -e

if [ -e laney-ubuntu-appstream-xenial.list ]; then
        add-apt-repository -r ppa:laney/appstream
fi

if [ -d /srv/appstream/appstream-generator ]; then
        rm -rf /srv/appstream/appstream-generator
fi

if [ -d /srv/appstream/as-installed ]; then
        rm -rf /srv/appstream/as-installed
fi

UBUNTU_HOMEDIR="$(getent passwd ubuntu | cut -d: -f6)"

if [ "${UBUNTU_HOMEDIR}" = "/srv/appstream" ]; then
        usermod -d /srv/appstream /home/ubuntu
        mv /srv/ubuntu/update-appstream.sh /home/ubuntu
fi

if id appstream 2>/dev/null; then
        userdel appstream
fi

# Run the install hook - this will install any new deps etc
. ${CHARM_DIR}/hooks/install
