#!/bin/sh

set -e

# If we don't have a mirror, quit (the deployment will mount this for us soon)
if ! grep -qs /srv/data /proc/mounts; then
    juju-log 'Deferring config-changed hook, since /srv/data is not yet mounted'
    exit 0
fi

juju-log 'Running config-changed hook'

HOSTNAME=$(config-get hostname)

if [ -n "${HOSTNAME}" ]; then
    juju-log "Got hostname ${HOSTNAME}"
fi

RELEASES=$(config-get releases)
COMPONENTS="main universe multiverse restricted"
ARCHES=$(config-get arches)
MIRROR=$(config-get mirror)

juju-log "Got releases ${RELEASES} and arches ${ARCHES} and mirror ${MIRROR}"

cat <<EOF | su - ubuntu
sed -e 's/#HOSTNAME#/${HOSTNAME:-$(hostname -f)}/' ${CHARM_DIR}/dep11-config.yml.in > /srv/data/appstream/appstream-workdir/dep11-config.yml
EOF

for r in ${RELEASES}; do
    for release in ${r} ${r}-proposed ${r}-updates ${r}-security ${r}-backports; do
        priority=0
        if [ ${release#${r}-} = "updates" ]; then
                priority=10
        fi
        if [ ${release#${r}-} = "security" ]; then
                priority=20
        fi
        if [ ${release#${r}-} = "proposed" ]; then
                priority=30
        fi
        if [ ${release#${r}-} = "backports" ]; then
                priority=40
        fi
        cat <<EOF >> /srv/data/appstream/appstream-workdir/dep11-config.yml
  ${release}:
    baseSuite: ${r}
    dataPriority: ${priority}
    components:
EOF
        for component in ${COMPONENTS}; do
            echo "      - ${component}" >> /srv/data/appstream/appstream-workdir/dep11-config.yml
        done

        echo "    architectures:" >> /srv/data/appstream/appstream-workdir/dep11-config.yml
        for arch in ${ARCHES}; do
            echo "      - ${arch}" >> /srv/data/appstream/appstream-workdir/dep11-config.yml
        done
        echo "    useIconTheme: Humanity" >> /srv/data/appstream/appstream-workdir/dep11-config.yml
    done
done

juju-log 'Adding proxy settings'

for var in http_proxy https_proxy no_proxy; do
    sed -i "/^${var}/d" /etc/environment
    v=$(config-get ${var})
    if [ -n "${v}" ]; then
        juju-log "Setting ${var}=${v}"
        echo "${var}=${v}" >> /etc/environment
    fi
done


cat <<EOF | su - ubuntu
set -e

sed -e 's/#RELEASES#/${RELEASES}/; s/#ARCHES#/${ARCHES}/; s/#MIRROR#/${MIRROR}/' ${CHARM_DIR}/update-appstream.sh.in > ~/update-appstream.sh

chmod a+x ~/update-appstream.sh

if ! crontab -l | grep -qs update-appstream; then
    echo "0 * * * * flock -xn ~/lock ~/update-appstream.sh" | crontab -
fi
if grep -qs /srv/data /proc/mounts && [ ! -e /home/ubuntu/lock ]; then
    flock -xn /home/ubuntu/lock /home/ubuntu/update-appstream.sh
fi
EOF
