#!/bin/sh

set -ex

juju-log 'Invoking charm-pre-install hooks'
[ -d exec.d ] && ( for f in exec.d/*/charm-pre-install; do [ -x $f ] && /bin/sh -c "$f"; done )

juju-log 'Installing appstream-dep11 dependencies'

# libcairo-gobject2 since python3-gi-cairo doesn't depend on it in 14.04,
# although it should (fixed in wily)
apt-get -y install gir1.2-rsvg-2.0 \
                   python3-apt \
                   python3-cairo \
                   python3-gi \
                   libcairo-gobject2 \
                   python3-gi-cairo \
                   python3-jinja2 \
                   python3-lxml \
                   python3-matplotlib \
                   python3-pil \
                   python3-pygments \
                   python3-setuptools \
                   python3-voluptuous \
                   python3-yaml

apt-get -y -t trusty-backports install python3-lmdb

juju-log 'Installing utilities'

# jq for config-changed hook
apt-get -y install git python-virtualenv debmirror

juju-log 'Installing web server'

apt-get -y install apache2

juju-log 'Installing rsyncd'

apt-get -y install rsync xinetd

juju-log 'Installing config files'

cat <<EOF > /etc/apache2/sites-available/appstream.conf
<Directory /srv/data/appstream/appstream-public>
    Options Indexes FollowSymLinks
    Require all granted
</Directory>

<Directory /srv/data/appstream/logs>
    Options Indexes
    Require all granted
</Directory>

<VirtualHost *:80>
    DocumentRoot /srv/data/appstream/appstream-public
    ErrorLog \${APACHE_LOG_DIR}/error.log
    CustomLog \${APACHE_LOG_DIR}/custom.log combined
    AddType 'text/plain' .log
    AddCharset UTF-8 .log
</VirtualHost>
EOF

sed -i "/^RSYNC_ENABLE/ s/=.*/=inetd/" /etc/default/rsync

cat <<EOF > /etc/xinetd.d/rsync
service rsync {
    disable = no
    socket_type = stream
    wait = no
    user = root
    server = /usr/bin/rsync
    server_args = --daemon
    log_on_failure += USERID
}
EOF

cat <<EOF > /etc/rsyncd.conf
max connections = 20
log file = /var/log/rsync.log
timeout = 300
use chroot = false

[appstream]
    path = /srv/data/appstream/appstream-public/data
    read only = yes
    list = yes
    uid = appstream
    gid = appstream
EOF

if ! getent passwd appstream > /dev/null; then
    addgroup --gid 11111 appstream >/dev/null 2>&1
    adduser --uid 11111 --gid 11111 --home /nonexistent --no-create-home --disabled-password --gecos "" appstream >/dev/null 2>&1
fi

rm -f /etc/apache2/sites-enabled/appstream.conf
ln -sf ../sites-available/appstream.conf /etc/apache2/sites-enabled/
service apache2 restart
open-port 80

service xinetd restart
open-port 873
