#!/bin/sh

set -e

# change code directory and virtualenv to appstream user, so code is owned by a
# different user than it is run as
if ! getent passwd appstream > /dev/null; then
    juju-log 'upgrade-charm: Creating user and group'
    addgroup --gid 11111 appstream >/dev/null 2>&1
    adduser --uid 11111 --gid 11111 --home /nonexistent --no-create-home --disabled-password --gecos "" appstream >/dev/null 2>&1

    juju-log 'upgrade-charm: Changing owner'
    chown -R appstream:appstream /srv/data/appstream/appstream-dep11 /srv/data/appstream/appstream
fi

# we used to host apache ourselves, but no more
if [ -e /etc/apache2/sites-enabled/appstream.conf ]; then
    juju-log 'upgrade-charm: Purging apache2'
    rm /etc/apache2/sites-enabled/appstream.conf /etc/apache2/sites-available/appstream.conf
    apt-get -y purge apache2
    close-port 80
fi

# Run the install hook - this will install any new deps etc
. ${CHARM_DIR}/hooks/install
